services:
  - type: web
    name: rudhra-bot
    repo: https://github.com/rudhachu/rudh.git
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false
        required: true
      - key: DATABASE_URL
        sync: false
        required: true
      - key: SUDO
        value: 919895809960
        required: true
      - key: MODE
        value: private
        required: true
